---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(readr)
library(ggplot2)
```

```{r}
noaa_data <- read_csv('carbon_dioxde_levels.csv')
head(noaa_data)
```

```{r}
noaa_viz <- ggplot(data = noaa_data, aes(x=Age_yrBP, y=CO2_ppmv)) + 
  geom_line() +
  labs(title = "Carbon Dioxide Levels From 8,000 to 136 Years BP", 
       subtitle = "From World Data Center for Paleoclimatology and NOAA Paleoclimatology Program", 
       x = "Years Before Today (0=1950)",
       y = "Carbon Dioxide Level (Parts Per Million)")

noaa_viz
```

```{r}
noaa_viz + scale_x_reverse(lim=c(800000,0))
```

```{r}
iac_data <- read_csv('yearly_co2.csv')

head(iac_data)
```

```{r}
iac_viz <- ggplot(data = iac_data, aes(x=year, y=data_mean_global)) +
  geom_line() +
  labs(title = "Carbon Dioxide Levels over Time",
       subtitle = "From Institute for Atmospheric and Climate Science (IAC).",
       x = "Year", y = "Carbon Dioxide Level (Parts Per Million)")

iac_viz
```

```{r}
millenia_max <- max(noaa_data$CO2_ppmv)
```

```{r}
iac_viz <- ggplot(data = iac_data, aes(x=year, y=data_mean_global)) +
  geom_line() +
  labs(title = "Carbon Dioxide Levels over Time",
       subtitle = "From Institute for Atmospheric and Climate Science (IAC).",
       x = "Year", y = "Carbon Dioxide Level (Parts Per Million)") +
  geom_hline(aes(yintercept = millenia_max, linetype = "Historical CO2 Peak before 1950"))

iac_viz
```
