---
title: "Dataframes"
author: "Gaurav"
date: "2024-02-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(readr)
```

```{r}
artists <- read.csv('artists.csv')
head(artists)
summary(artists)
```

Piping:

```{r}
artists %>%
  summary()
```

Selecting columns:

```{r}
group_info <- artists %>%
  select(group, spotify_monthly_listeners, year_founded)

group_info
```

```{r}
no_albums <- artists %>%
  select(-albums)

no_albums
```

```{r}
df_cols_removed <- artists %>%
  select(-genre, -spotify_monthly_listeners, -year_founded)

df_cols_removed
```

Filtering rows with logic I:

```{r}
rock_groups <- artists %>%
  filter(genre == 'Rock')

rock_groups
```

```{r}
artists

popular_rock_groups <- artists %>%
  filter(genre == 'Rock', spotify_monthly_listeners > 20000000)

popular_rock_groups
```

Filtering rows with logic II:

```{r}
korea_or_before_2000 <- artists %>%
  filter(country == 'Korea' | year_founded < 2000)

korea_or_before_2000

not_rock_groups <- artists %>%
  filter(genre != 'Rock')

not_rock_groups
```

Arranging rows:

```{r}
group_asc <- artists %>%
  arrange(group)

group_asc

yt_desc <- artists %>%
  arrange(desc(youtube_subscribers)) %>%
  select(group)

yt_desc
```

Review dataframe:

```{r}
chosen_cols <- artists %>%
  select(-country, -year_founded, -albums)

chosen_cols
```

```{r}
popular_not_hip_hop <- chosen_cols %>%
  filter(spotify_monthly_listeners > 20000000, genre != 'Hip Hop')

popular_not_hip_hop
```

```{r}
yt_desc <- popular_not_hip_hop %>%
  arrange(desc(youtube_subscribers))

yt_desc
```

Compare output with above 3 blocks:

```{r}
artists <- artists %>%
  select(-country, -year_founded, -albums) %>%
  filter(spotify_monthly_listeners > 20000000, genre != 'Hip Hop') %>%
  arrange(desc(youtube_subscribers))

artists
```
